# These are packages that are related to configuring parts of the system.

packages:
  # Configuring SSH keys, cloud provider check-in, etc
  # TODO: needs Ignition kargs
  # - afterburn afterburn-dracut
  # NTP support
  - chrony
  # Storage configuration/management
  - lvm2
  - cryptsetup
  - e2fsprogs
  - sg3_utils
  - xfsprogs
  ## This is generally useful... https://github.com/CentOS/centos-bootc/issues/394
  - cloud-utils-growpart
  # User configuration
  - passwd
  - shadow-utils
  - acl
  # Manipulating the kernel keyring; used by bootc
  - keyutils
  # There are things that write outside of the journal still (such as the
  # classic wtmp, etc.). auditd also writes outside the journal but it has its
  # own log rotation.
  # Anything package layered will also tend to expect files dropped in
  # /etc/logrotate.d to work. Really, this is a legacy thing, but if we don't
  # have it then people's disks will slowly fill up with logs.
  - logrotate
  # Boost starving threads
  # https://github.com/coreos/fedora-coreos-tracker/issues/753
  - stalld
