name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-atomic:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - atomic-base
          - atomic-gnome
          - atomic-kde

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Install Homebrew
        uses: homebrew/actions/setup-homebrew@master

      - name: Setup Podman
        run: |
          brew install podman
          podman --version

      - name: Build Image
        run: |
          sudo su
          just build-atomic ${{ matrix.images }}
