name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-atomic:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        images:
          - base
          - gnome
          - kde

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Update podman
        run: |
          # from https://askubuntu.com/questions/1414446/whats-the-recommended-way-of-installing-podman-4-in-ubuntu-22-04
          ubuntu_version='22.04'
          key_url="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key"
          sources_url="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}"
          echo "deb $sources_url/ /" | sudo tee /etc/apt/sources.list.d/devel-kubic-libcontainers-unstable.list
          curl -fsSL $key_url | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
          sudo apt update
          sudo apt install -y podman

      - name: Build Image
        run: |
          just build-atomic ${{ matrix.images }}

      - name: Run Image
        run: podman run --rm -ti localhost/fedora-bootc-atomic-${{ matrix.images }}:latest bootc --help

      # - name: Tag Image
      #   env:
      #     ORIG_IMAGE: localhost/fedora-bootc-atomic-${{ matrix.images }}:latest
      #     GHCR_REPO: ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}
      #   run: |
      #     podman tag $ORIG_IMAGE $GHCR_REPO:${{ github.sha }}
      #     podman tag $ORIG_IMAGE $GHCR_REPO:latest

      - name: Push Image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: localhost/fedora-bootc-atomic-${{ matrix.images }}:latest
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
